api/urls.py
from django.urls import path, include

from rest_framework.routers import SimpleRouter
from .api_views import (
    CategoryListAPIView,
    SmartphoneViewSet,
    NotebookViewSet,
)

router = SimpleRouter()
router.register('smartphones', SmartphoneViewSet, basename='smartphones')
router.register('notebooks', NotebookViewSet, basename='notebooks')

urlpatterns = [
    path('', include(router.urls)),
    path('categories/', CategoryListAPIView.as_view(), name='categories'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('', include('allauth.urls')),
    path('api/', include('api.urls')),
    # path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += [re_path(r'^.*', TemplateView.as_view(template_name='index.html'))]pip install -U "celery[redis]"

products/urls.py
from django.urls import path

from .views import (
    ProductDetailView, 
    CategoryDetailView, 
    BaseView, 
    CartView, 
    AddToCartView, 
    DeleteFromCartView,
    ChangeQtyView,
    CheckoutView,
    MakeOrderView
)

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>/', ChangeQtyView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order')
]

products/models.py
import sys

from PIL import Image

from django.urls import reverse
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.utils import timezone

from io import BytesIO

# Create your models here.

User = get_user_model()


def get_models_for_count(*models_name):
    return [models.Count(model_name) for model_name in models_name]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


def get_upload_path(instance, filename):
    name = instance.title
    return f'products/{name}/{filename}'


class MinResolutionError(Exception):
    pass


class MaxResolutionError(Exception):
    pass


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to),
                                  reverse=True)
        return products


class LatestProducts:
    objects = LatestProductsManager()


class CategoryManager(models.Manager):
    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count',
        'Смартфоны': 'smartphone__count',
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name])) for c
            in qs
        ]
        print([type(i.name) for i in qs])
        return data


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="Имя категории")
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):
    MIN_RESOLUTION = (800, 800)

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name="Наименование")
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=get_upload_path, verbose_name="Изображение")
    description = models.TextField(verbose_name="Описание", null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Цена")

    def save(self, *args, **kwargs):
        # image = self.image
        # img = Image.open(image)
        # min_height, min_width = self.MIN_RESOLUTION
        # max_height, max_width = self.MAX_RESOLUTION
        # if img.height > max_height or img.width > max_width:
        #     raise MaxResolutionError('Разрешение изображения больше максимального!')
        # if img.height < min_height or img.width < min_width:
        #     raise MinResolutionError('Разрешение изображения меньше минимального!')
        image = self.image
        img = Image.open(image)
        new_img = img.convert('RGB')
        new_img.thumbnail((800, 800), Image.ANTIALIAS)
        filestream = BytesIO()
        new_img.save(filestream, 'JPEG', quality=90)
        filestream.seek(0)
        self.image = InMemoryUploadedFile(
            filestream, 'ImageField', self.image.name, 'jpeg/image', sys.getsizeof(filestream), None
        )
        super().save(*args, **kwargs)

    def get_model_name(self):
        return self._meta.model_name

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Notebook(Product):
    diagonal = models.CharField(max_length=255, verbose_name="Диагональ")
    display_type = models.CharField(max_length=255, verbose_name="Тип диплея")
    processor_freq = models.CharField(max_length=255, verbose_name="Часота процессора")
    ram = models.CharField(max_length=255, verbose_name="Оперативная память")
    video = models.CharField(max_length=255, verbose_name="Видеокарта")
    time_without_charge = models.CharField(max_length=255, verbose_name="Время работы аккумулятора")


class Smartphone(Product):
    diagonal = models.CharField(max_length=255, verbose_name="Диагональ")
    display_type = models.CharField(max_length=255, verbose_name="Тип диплея")
    resolution = models.CharField(max_length=255, verbose_name="Разрешение экрана")
    accum_volume = models.CharField(max_length=255, verbose_name="Объем батареи")
    ram = models.CharField(max_length=255, verbose_name="Оперативная память")
    sd = models.BooleanField(default=True, verbose_name="Наличие SD карты")
    sd_volume = models.CharField(max_length=255, null=True, blank=True,
                                 verbose_name="Максимальный объем встраиваемой памяти")
    main_cam_mp = models.CharField(max_length=255, verbose_name="Главная камера")
    frontal_cam_mp = models.CharField(max_length=255, verbose_name="Фронтальная камера")


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name="Покупатель", on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name="Корзина", on_delete=models.CASCADE, related_name="related_products")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    total_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Общая цена")

    def get_model_name(self):
        return self.content_object._meta.model_name

    def __str__(self):
        return f'Продукт {self.content_object.title} (для корзины)'

    def save(self, *args, **kwargs):
        self.total_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey('Customer', null=True, verbose_name="Владелец", on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name="related_cart")
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name="Общая цена")
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return f'ID {self.id}, {self.owner.user.email}'

    def save(self, *args, **kwargs):
        try:
            cart_data = self.products.aggregate(models.Sum('total_price'), models.Count('id'))
            if cart_data.get('total_price__sum'):
                self.final_price = cart_data['total_price__sum']
            else:
                self.final_price = 0
            self.total_products = cart_data['id__count']
        except:
            pass
        super().save(*args, **kwargs)


class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name="Номер телефона", null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name="Адреc", null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name="Заказы покупателя", related_name='related_customer')

    def __str__(self):
        return f'Покупатель {self.user.email}'


class Order(models.Model):
    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_preogress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOISES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ сформирован'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    BUYING_TYPE_CHOISES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='related_orders',
                                 on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name="Имя")
    last_name = models.CharField(max_length=255, verbose_name="Фамилия")
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name="Адрес", null=True, blank=True)
    status = models.CharField(max_length=100,
                              verbose_name="Статус заказа",
                              choices=STATUS_CHOISES,
                              default=STATUS_NEW
                              )
    buying_type = models.CharField(max_length=100,
                                   verbose_name="Способ получения",
                                   choices=BUYING_TYPE_CHOISES,
                                   default=BUYING_TYPE_SELF
                                   )
    comment = models.TextField(verbose_name="Комментарий к заказу", blank=True, null=True)

products/forms.py
from django import forms

from .models import Order

class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = "Дата получения заказа"

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment',
        )

products/templates/products/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_sd').on('click', function(){
        if($('#id_sd').prop('checked') == true){
            $('#id_sd_volume').prop('readonly',false)
            $('#id_sd_volume').val('')
            $('#id_sd_volume').css('background', 'white')
        }else{
            $('#id_sd_volume').prop('readonly', true)
            $('#id_sd_volume').val('')
            $('#id_sd_volume').css('background', 'lightgrey')
        }
    })
})(django.jQuery);
</script>
{% endblock %}

products/templates/products/cart.html
{% extends 'base.html' %}

{% block content %}
  <h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %} пуста {% endif %}</h3>
  {% if cart.products.count %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Наименование</th>
          <th scope="col">Изображение</th>
          <th scope="col">Цена</th>
          <th scope="col">Количество</th>
          <th scope="col">Общая цена</th>
          <th scope="col">Действие</th>
        </tr>
      </thead>
      <tbody>
          {% for item in cart.products.all %}
            <tr>
                <th scope="row">{{ item.content_object.title }}</th>
                <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid"></td>
                <td>{{ item.content_object.price }} руб.</td>
                <td>
                  <form action="{% url 'change_qty' ct_model=item.get_model_name slug=item.content_object.slug %}" method="POST">
                    {% csrf_token %}
                    <input type="number" class="form-control" min="1" value="{{ item.qty }}" name="qty">
                    <input type="submit" class="btn btn-primary" value="Изменить кол-во">
                  </form>
                </td>
                <td>{{ item.total_price }} руб.</td>
                <td><a href="{% url 'delete_from_cart' ct_model=item.get_model_name slug=item.content_object.slug %}"><button class="btn btn-danger">Удалить</button></a></td>
            </tr>
        {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td>Итого:</td>
          <td> {{ cart.total_products }}</td>
          <td> <strong>{{ cart.final_price }} руб.</strong></td>
          <td><a href="{% url 'checkout' %}"><button class="btn btn-primary">Перейти к оформлению</button></a></td>
        </tr>
      </tbody>
    </table>
  {% endif %}
{% endblock content %}

products/templates/products/category_detail.html
{% extends 'base.html' %}

{% block content %}
<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item active">{{ category.name }}</li>
    </ol>
</nav>
<div class="row">
    {% for product in category_products %}
        <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5>₽{{ product.price }}</h5>
                <p class="card-text"><a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}" class="btn btn-danger">Добавить в корзину</a></p>
            </div>
            <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
            </div>
        </div>
        </div>
    {% endfor %}
</div>

{% endblock content %} 

products/templates/products/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class="text-center mt-5 mb-5">Оформление заказа</h3>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Наименование</th>
        <th scope="col">Изображение</th>
        <th scope="col">Цена</th>
        <th scope="col">Количество</th>
        <th scope="col">Общая цена</th>
      </tr>
    </thead>
    <tbody>
        {% for item in cart.products.all %}
          <tr>
              <th scope="row">{{ item.content_object.title }}</th>
              <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid"></td>
              <td>{{ item.content_object.price }} руб.</td>
              <td>{{ item.qty }}</td>
              <td>{{ item.total_price }} руб.</td>
          </tr>
      {% endfor %}
      <tr>
        <td colspan="2"></td>
        <td>Итого:</td>
        <td> {{ cart.total_products }}</td>
        <td> <strong>{{ cart.final_price }} руб.</strong></td>
      </tr>
    </tbody>
  </table>
<hr>
<h3 class="text-center mt-5 mb-5">Форма заказа</h3>
<form action="{% url 'make_order' %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success btn-block mb-3" value="Оформить заказ">
</form>

{% endblock content %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load specification %}
{% block content %}
<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{{ product.category.get_absolute_url }}">{{product.category}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
    </ol>
</nav>
<div class="row">
    <div class="col-md-4">
        <img src="{{product.image.url}}" class="img-fluid">
    </div>
    <div class="col-md-8">
        <h3>{{ product.title }}</h3>
        <p>Цена: {{ product.price }} руб.</p>
        <p>Описание: {{ product.description }}</p>
        <hr>
        <a href="{% url 'add_to_cart' ct_model=ct_model slug=product.slug %}"><button class="btn btn-danger">Добавить в корзину</button></a>
    </div>
    <p class="mt-4">Характеристики: </p>

    {{ product|product_spec }}

</div>

{% endblock content %}